server.port=8081
spring.application.name=auth-service

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/auth_db}

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME:}
spring.mail.password=${GMAIL_APP_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

verification.strategy=${VERIFICATION_STRATEGY:otp}
verification.base-url=${VERIFICATION_BASE_URL:http://localhost:8081/api/auth/verify/link}
